### ISSUE TITLE
login issu

### ISSUE THREAD

**Issue by sahil9049** [Jaisilan7565/Gym-Management-Application#1]
what is pass for admin page dirct login activity open in admin app

**Comment by Jaisilan7565** [comment]
This application, designed for a Solo Gym Business, starts with the developer creating the initial admin account via the Firebase Console. The gym owner, acting as the admin, then manages the creation of trainer and trainee accounts through the app's interface. If you wish to use this project, you can connect it to your Firebase, configure it for real-time database functionality, and set up email and password authentication. You can also create your admin login credentials through your Firebase Console.

**Comment by Jaisilan7565** [comment]
> what is pass for admin page dirct login activity open in admin app

This application, designed for a Solo Gym Business, starts with the developer creating the initial admin account via the Firebase Console. The gym owner, acting as the admin, then manages the creation of trainer and trainee accounts through the app's interface. If you wish to use this project, you can connect it to your Firebase, configure it for real-time database functionality, and set up email and password authentication. You can also create your admin login credentials through your Firebase Console.
